### ISSUE TITLE
Cursor issue in MODE 12

### ISSUE THREAD

**Issue by eightbitswide** [avalonbits/aed#23]
Running AED in mode 12. 

Hit enter a few times to create new lines, then using backspace leaves cursor behind at the left of each line deleted.

**Comment by avalonbits** [comment]
Which version of AED are you using?

**Comment by avalonbits** [comment]
Never mind. Tested in 3 different modes and it has the same behavior.

**Comment by avalonbits** [comment]
This fix will be on the next release.

**Comment by avalonbits** [comment]
Version [v0.11.0](https://github.com/avalonbits/aed/releases/tag/v0.11.0) was released, contains the fix.

**Comment by eightbitswide** [comment]
Awesome.  Thank you
